export { Hero } from "./hero";
export { Skills } from "./skills";
export { Education } from "./education";
export { Experience } from "./experience";
export { Projects } from "./projects";
export { Achievements } from "./achievements";
export { Contact } from "./contact";
export { Footer } from "./footer";
export { SectionWrapper } from "./section-wrapper";
export { AIAgent, openAIChat } from "./ai-agent";
